### ISSUE TITLE
try to change banner

### ISSUE THREAD

**Issue by ymansiaux** [ThinkR-open/signature#20]
## Critères de validation 

- [x] L'application doit être MàJ avec la nouvelle image

![image](https://user-images.githubusercontent.com/49268931/213511255-e879d122-5d36-4220-b29a-919b3e77641d.png)

- [x] La bannière de l'email doit correspondre à la nouvelle image

![image](https://user-images.githubusercontent.com/49268931/213511349-c755b9c4-078a-4495-8fdc-d3e8aff675cc.png)

**Comment by ymansiaux** [comment]
@ArthurData  tout est OK

**Comment by ArthurData** [comment]
Top, je valide :))
